BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ' || 'TestDateTimeTable';
EXCEPTION
WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
    END IF;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ' || 'TestObjectTypeTable';
EXCEPTION
WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
    END IF;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ' || 'TestNestedObjectTypeTable';
EXCEPTION
WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
    END IF;
END;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ' || 'TestVarrayTable';
EXCEPTION
WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
    END IF;
END;

ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-RR HH:MI:SS AM';
ALTER session set NLS_TIMESTAMP_TZ_FORMAT = 'DD-MON-RR HH:MI:SS AM TZR';

CREATE TABLE TestDateTimeTable(
    PK NUMBER GENERATED ALWAYS AS IDENTITY,
    COL_INTERVAL_YEAR_TO_MONTH INTERVAL YEAR TO MONTH,
    COL_INTERVAL_DAY_TO_SECOND INTERVAL DAY(9) TO SECOND(9),
    PRIMARY KEY(PK)
);

CREATE OR REPLACE TYPE OBJECT_TYPE OID '19A57209ECB73F91E03400400B40BB23' AS OBJECT(
    STRING_ATTR VARCHAR(20), 
    INT_ATTR NUMBER, 
    FLOAT_ATTR FLOAT, 
    DECIMAL_ATTR FLOAT
);

CREATE TABLE TestObjectTypeTable(
    PK NUMBER GENERATED ALWAYS AS IDENTITY, 
    COL_OBJECT OBJECT_TYPE, 
    PRIMARY KEY(PK) 
);

CREATE OR REPLACE TYPE NESTED_TYPE OID '19A57209ECB73F91E03400400B40BB25' AS OBJECT(
    STRING_ATTR VARCHAR2(20),
    OBJECT_ATTR OBJECT_TYPE,
    MAP MEMBER FUNCTION GET_ATTR1 RETURN NUMBER
);

CREATE TABLE TestNestedObjectTypeTable(
    PK NUMBER GENERATED ALWAYS AS IDENTITY,
    COL_NESTED_OBJECT NESTED_TYPE,
    PRIMARY KEY(PK)
);

CREATE OR REPLACE TYPE CharArrayType AS VARRAY(6) OF VARCHAR(100);
CREATE OR REPLACE TYPE ByteArrayType AS VARRAY(6) OF RAW(100);
CREATE OR REPLACE TYPE IntArrayType AS VARRAY(6) OF NUMBER;
CREATE OR REPLACE TYPE BoolArrayType AS VARRAY(6) OF NUMBER;
CREATE OR REPLACE TYPE FloatArrayType AS VARRAY(6) OF FLOAT;
CREATE OR REPLACE TYPE DecimalArrayType AS VARRAY(6) OF NUMBER;

CREATE TABLE TestVarrayTable(
    PK NUMBER GENERATED ALWAYS AS IDENTITY,
    COL_CHARARR CharArrayType,
    COL_BYTEARR ByteArrayType,
    COL_INTARR IntArrayType,
    COL_BOOLARR BoolArrayType,
    COL_FLOATARR FloatArrayType,
    COL_DECIMALARR DecimalArrayType,
    PRIMARY KEY(PK)
);
