[package]
org = "wso2"
name = "online_shop"
version = "0.0.1"

[build-options]
cloud = "k8s"

[[platform.java17.dependency]]
groupId = "com.oracle.database.jdbc"
artifactId = "ojdbc11"
version = "23.2.0.0"

[[platform.java17.dependency]]
groupId = "com.oracle.database.xml"
artifactId = "xdb"
version = "23.2.0.0"

[[platform.java17.dependency]]
groupId = "com.oracle.database.xml"
artifactId = "xmlparserv2"
version = "23.2.0.0"
